### PR TITLE
Fixes so PDF reports get rendered on odoo11

### PR DESCRIPTION
**Pull request by kristroma**
Hi there, 

I'm from a New Zealand company, we use formio for our clients on odoo11 & odoo14.

So there were some issues we discovered regarding printing PDF reports (available udner Print menu on formio.form objects), and I was able to fix them by the changes I've committed. 

Cheers,
Kristina

### CODE REVIEW

**Comment by bobslee** [comment]
Hi Kristina,
Thanks for the PR.

The change for the `required` property is indeed a nice fix!

**The `columnsComponent`**

I'm not sure about the change in the `columnsComponent` its `rows` function.
This could lead to other issues. Did you run the unit tests?
And could you provide me (eg. email) the JSON of the columns component? (click on its wrench icon: edit JSON).

It seems like the components didn't got an `id` key/value in the Builder JSON right?
This could be caused by an ***older*** **formio.js version**, which is still included in the Odoo 11 until 14 modules.
Could this be the case, the missing `id(s)` in the Builder JSON?

The missing`id(s)`can be generated with a newer **formio.js** library version.
You can download and install a library version within Odoo, via the menu: 
*Configuration >> formio.js Versions (github tags)*

Let me know whether this solves or what you think about this.
Thanks!

**Comment by bobslee** [comment]
Additional...
To generate the missing `ids` you need to modify the **formio.js version** in the (odoo) **Builder**.
Then you need to open the form builder and change something eg a label or such.
This shall generate the missing `ids`.

**Comment by kristroma** [comment]
Hi Bob,

You've guessed it right - we don't have "id" in our component JSON hence the issue on printing. 
I've emailed you JSON of our builder. Our JS version is 4.9.26 btw - I thought it's the latest supported on Odoo11?

Thanks a lot of help, getting there!
Kristina

**Comment by bobslee** [comment]
Hi @kristroma 
I just send you a mail with some info.
I hope this clarifies and solves for you. If solved, please close the issue.

I suppose you know the formio.js library (and its versions) has nothing to do with Odoo, in terms of JavaScript / frontend capabilities.
As far as I know, recent versions > 4.9.x work fine with the Odoo module.

**Comment by kristroma** [comment]
Hi @bobslee 

Thanks a lot for your help, I'll test tomorrow what versions of the js library resolves the issue.
I've just updated the PR so it only has a change for required property.

Cheers,
Kristina

**Pull request merged**
